[package]
name = "peios"
version = "0.2.0"
edition = "2021"
license = "MIT"
description = "Safe, idiomatic Rust bindings to libpeios"

[features]
default = []
static = ["peios-sys/static"]
uapi = ["peios-sys/uapi"]

[dependencies]
bitflags = "2.13.0"
libc = "0.2"
peios-sys = { path = "../peios-sys", version = "0.2.0" }
